"""Target and Bench schemas for ShopProbe.

Implements the typed I/O contract documented in
``docs/specs/shop_arena/web_probe_patch.md`` (which supersedes the pair
semantics in ``web_probe.md`` §5.2):

* :class:`Target` — a deployed storefront under test. The ``label`` field
  is a closed literal (``"sandbox"`` or ``"real"``) and the ``name`` field
  is a filename-friendly identifier with no join semantics.
* :class:`Bench` — two flat populations (``sandboxes`` and ``reals``) that
  the structural-fidelity instrument compares group-vs-group.

The module is import-safe: it performs no I/O at import time. YAML loading
lives in :mod:`shop_arena.probe.bench`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

TargetLabel = Literal["sandbox", "real"]
"""Population a target belongs to (web_probe_patch).

* ``sandbox`` — a SandboxShop generated by ShopArena.
* ``real`` — a production storefront.
"""


class Target(BaseModel):
    """A deployed storefront under test.

    Attributes:
        name: Filename-friendly identifier (e.g. ``"shop_alpha"``,
            ``"real_a"``). No join semantics — two targets in different
            groups may not share a name (see :class:`Bench`).
        base_url: Base URL of the storefront. Crawls and probes are
            rooted here.
        label: Population this target belongs to (see :data:`TargetLabel`).
        data_dir: Optional path to a directory holding ``products.json``
            and ``collections.json`` for the storefront's catalog. The
            ``type: scale`` rubric entry reads catalog counts from this
            directory; when ``None``, catalog metrics in
            :class:`shop_arena.probe.scale.metrics.ScaleMetrics` are ``None``
            and the per-page richness fields still compute.
        notes: Free-form operator notes; ``None`` if unset.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    name: str = Field(min_length=1)
    base_url: str = Field(min_length=1)
    label: TargetLabel
    data_dir: Path | None = None
    notes: str | None = None


class Bench(BaseModel):
    """Two flat populations of storefronts compared group-vs-group.

    Per ``web_probe_patch.md`` the bench replaces the prior ``Cohort``:
    pair identity is gone, both groups are flat lists, and every target's
    ``name`` is unique across the entire bench.

    Attributes:
        version: Bench schema version (e.g. ``"0.1"``).
        sandboxes: SandboxShop targets (every entry has
            ``label == "sandbox"``).
        reals: Real storefront targets (every entry has
            ``label == "real"``).
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    version: str = Field(min_length=1)
    sandboxes: tuple[Target, ...] = ()
    reals: tuple[Target, ...] = ()

    @model_validator(mode="after")
    def _check_group_labels(self) -> Bench:
        """Reject a target whose ``label`` disagrees with the group it appears in."""
        for target in self.sandboxes:
            if target.label != "sandbox":
                msg = (
                    f"bench: sandboxes entry {target.name!r} has "
                    f"label={target.label!r}; expected 'sandbox'"
                )
                raise ValueError(msg)
        for target in self.reals:
            if target.label != "real":
                msg = (
                    f"bench: reals entry {target.name!r} has "
                    f"label={target.label!r}; expected 'real'"
                )
                raise ValueError(msg)
        return self

    @model_validator(mode="after")
    def _check_unique_names(self) -> Bench:
        """Reject benches that reuse a ``name`` across the union of groups."""
        seen: set[str] = set()
        for target in (*self.sandboxes, *self.reals):
            if target.name in seen:
                msg = f"bench: duplicate target name {target.name!r}"
                raise ValueError(msg)
            seen.add(target.name)
        return self
